# Generated by Django 1.9.10 on 2016-10-19 17:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aldrynclouduser',
            options={'verbose_name': 'Aldryn SSO user', 'verbose_name_plural': 'Aldryn SSO users'},
        ),
    ]
