# Generated by Django 4.2.11 on 2024-03-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_sso', '0003_auto_20170528_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aldrynclouduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
